"""obscene table

Revision ID: 4170a9f8ba51
Revises: a44e81df0712
Create Date: 2023-06-06 19:52:31.136634

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '4170a9f8ba51'
down_revision = 'a44e81df0712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obscene_words',
    sa.Column('word', sa.String(length=25), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obscene_words')
    # ### end Alembic commands ###
