services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    command: sh -c "cd bot/core/db/ && alembic upgrade head"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  postgres_data:
