services:
  db:
    image: postgres:15.3
    container_name: rehab_postgres
    user: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rehab_network
    env_file:
      - ../.env

  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: rehab_backend
    restart: unless-stopped
    command: sh -c "cd bot/core/db/ && alembic upgrade head && python -u /app/application.py"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rehab_network
    env_file:
      - ../.env

networks:
  rehab_network:
    driver: bridge

volumes:
  postgres_data:
