# MENU
MENU = "MENU"
NAME = "NAME"
DESCRIPTION = "DESCRIPTION"
PARENT = "PARENT"
CHILD = "CHILD"

# FORM APPLICATION
FORM = "FORM"
MODEL = "MODEL"
DATA = "DATA"
SHOW_DATA = "SHOW_DATA"
FIELDS = "FIELDS"
FIELD_INDEX = "FIELD_INDEX"
FIELD_EDIT = "FIELD_EDIT"
COMPLETE = "COMPLETE"

# QUESTIONS
TITLE = "TITLE"
TEXT = "TEXT"
HINT = "HINT"
