"""removed spam table

Revision ID: 3cade9be208e
Revises: 40f2f23bb732
Create Date: 2023-06-20 18:44:09.246825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cade9be208e'
down_revision = '40f2f23bb732'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spam_ml_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_ml_data',
    sa.Column('cls', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='spam_ml_data_pkey')
    )
    # ### end Alembic commands ###
