"""spam ml data table

Revision ID: 40f2f23bb732
Revises: 4170a9f8ba51
Create Date: 2023-06-16 14:57:32.636966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f2f23bb732'
down_revision = '4170a9f8ba51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_ml_data',
    sa.Column('cls', sa.String(length=5), nullable=True),
    sa.Column('text', sa.String(length=999), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spam_ml_data')
    # ### end Alembic commands ###
