"""relationship

Revision ID: 619a16b88e80
Revises: 79afeb697c1e
Create Date: 2023-06-02 22:51:54.140566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619a16b88e80'
down_revision = '79afeb697c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
