"""relationship

Revision ID: 763f393456ac
Revises: 619a16b88e80
Create Date: 2023-06-02 22:59:34.658608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763f393456ac'
down_revision = '619a16b88e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
