"""relationship

Revision ID: 79afeb697c1e
Revises: ee0731b3b11b
Create Date: 2023-06-02 22:50:20.933309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79afeb697c1e'
down_revision = 'ee0731b3b11b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
