"""rename tables

Revision ID: 8e5e76d0cf18
Revises: 00b705dcce95
Create Date: 2023-06-03 22:03:33.819994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5e76d0cf18'
down_revision = '00b705dcce95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_data',
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_filter_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sticker_count', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['last_message_id'], ['message_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('message_table')
    op.drop_table('filter_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_table',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sticker_count', sa.INTEGER(), nullable=False),
    sa.Column('previous_message_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['previous_message_id'], ['message_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message_table',
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('sticker', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_filter_data')
    op.drop_table('message_data')
    # ### end Alembic commands ###
