"""relationship

Revision ID: 9776370711c2
Revises: ead96d0b356e
Create Date: 2023-06-02 23:10:03.546695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9776370711c2'
down_revision = 'ead96d0b356e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_table',
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sticker_count', sa.Integer(), nullable=False),
    sa.Column('previous_message_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['previous_message_id'], ['message_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('custommessage')
    op.drop_table('userfiltereddata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfiltereddata',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sticker_count', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('custommessage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('filter_table')
    op.drop_table('message_table')
    # ### end Alembic commands ###
