"""utcnow default, date > timestamp

Revision ID: c60d3e5f6a74
Revises: 8e5e76d0cf18
Create Date: 2023-06-04 14:35:10.061729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60d3e5f6a74'
down_revision = '8e5e76d0cf18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_data', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('message_data', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_data', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_column('message_data', 'timestamp')
    # ### end Alembic commands ###
