"""First migration

Revision ID: d0ff87fd6f69
Revises: e3088a21e432
Create Date: 2023-06-02 17:44:19.305117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ff87fd6f69'
down_revision = 'e3088a21e432'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
