"""First migration

Revision ID: e3088a21e432
Revises: 20e73d882f3c
Create Date: 2023-06-02 17:09:49.166833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3088a21e432'
down_revision = '20e73d882f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfiltereddata',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sticker_count', sa.Integer(), nullable=False),
    sa.Column('previous_message', sa.String(length=3000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfiltereddata')
    # ### end Alembic commands ###
