"""relationship

Revision ID: ead96d0b356e
Revises: 763f393456ac
Create Date: 2023-06-02 23:03:35.609122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead96d0b356e'
down_revision = '763f393456ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custommessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custommessage')
    # ### end Alembic commands ###
