"""relationship

Revision ID: ee0731b3b11b
Revises: d0ff87fd6f69
Create Date: 2023-06-02 22:47:41.496031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0731b3b11b'
down_revision = 'd0ff87fd6f69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userfiltereddata', 'previous_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfiltereddata', sa.Column('previous_message', sa.VARCHAR(length=3000), nullable=True))
    # ### end Alembic commands ###
